name: Tests
on: push
jobs: 
  init: 
    runs-on: ubuntu-latest
    container: node:18.10.0
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-varsion: [ 1.18.* ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup environment variables
        run: |
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "API_VERSION=${{ secrets.API_VERSION }}" >> .env
          echo "API_CLIENT_URL=${{ secrets.API_CLIENT_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_ACCESS_EXPIRES=${{ secrets.JWT_ACCESS_EXPIRES }}" >> .env 
          echo "JWT_REFRESH_EXPIRES=${{ secrets.JWT_REFRESH_EXPIRSE }}" >> .env 
          echo "REFRESH_TOKEN_COOKIE_NAME=${{ secrets.REFRESH_TOKEN_COOKIE_NAME }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
      - name: Install dependecies
        run: npm install
      - name: Prisma connection db
        run: npx prisma db push
      - name: Building project
        run: npm run build
      - name: Unit tests
        run: npm run test
      - name: E2E tests
        run: npm run test:e2e
